main/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.home,name="home"),
    path('signup',views.register,name="register"),
    path('signup_edit',views.signup_edit,name="signup_edit"),
    path('login',views.loginform,name="login"),
    path('logout',views.logout_form,name="logout"),
    path('opencv',views.stone_paper_scissor,name="opencv"),
    path('project/<str:pk>/',views.project,name="project"),
    path('object_detector',views.object_detecter,name="object_detector"),
    path('profile',views.profile,name="profile"),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    username = models.CharField(max_length=100,unique=True)
    email = models.EmailField(max_length=100,unique=True)
    firstname = models.CharField(max_length=100,null = True,blank=True)
    lastname = models.CharField(max_length=100,null = True,blank=True)
    profile_image = models.ImageField(upload_to='D:\PROJECT NM\Scripts\project\static\data',null = True,blank=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    def __str__(self):
        return self.username

class Project(models.Model):
    host = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    template = models.ImageField(upload_to='D:\PROJECT NM\Scripts\project\static\data',null = True,blank=True)
    discription = models.TextField()
    likes = models.ManyToManyField(User,related_name="prj_likes")
    dislikes = models.ManyToManyField(User,related_name="prj_dislikes")
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title

class comment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    project = models.ForeignKey(Project,on_delete=models.CASCADE)
    comment = models.TextField(null=True,blank=True)
    likes = models.ManyToManyField(User,related_name="cmt_likes")
    dislikes = models.ManyToManyField(User,related_name="cmt_dislikes")
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment[:50]


class ObjectDetector(models.Model):
    image = models.ImageField(upload_to='D:\PROJECT NM\Scripts\project\data',null = True,blank=True)

templates/RPS_match.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>match getter</title>
    <link rel="stylesheet" href="/static/styles/rps.css? {% now 'U' %}">

</head>
<body>
    <header>
        <h1>project-dj</h1>
    </header>
    <div class="content">
        
        <div class="game_logo">
            <img src="static\assests\rock-paper-scissors.png" alt="">
            <div class="title"><h1>rock-paper-scissors</h1></div>
        </div>
        <div class="image_field">
            {% if mode == "match getter" %}
                <img src="\static\assests\selector.jpg" alt="" srcset="">
            {% else %}
                {% if points_ai > points_user %}
                    <img src="\static\assests\sad.jpg" alt="" srcset="">
                {% elif points_user > points_ai%}
                    <img src="\static\assests\userwon.jpg" alt="" srcset="">
                {% else %}
                    <img src="\static\assests\draw.jpg" alt="" srcset="">
                {% endif %}
            {% endif %}
        </div>
    </div>
    <div class="container">
        <main>
            {% if mode == "match getter" %}
                <div class="match_getter"> 
                    <h1>select one of the mode give below</h1>
                    <form action="" method="post">
                        {% csrf_token %}
                        <button name="count" value="3">3x Matchs</button>
                        <button name="count" value="5">5x Matchs</button>
                        <button name="count" value="10">10x Matchs</button>
                    </form>
                </div>
                <a href="{%url 'home' %}"><button  class="back-btn"><span class="span"><--</span>home</button></a>

            {% else %}
                <div class="match_getter">
                        {% if points_ai > points_user %}
                            <h1 class="winner">computer wins!!!</h1>
                        {% elif points_user > points_ai %}
                            <h1 class="winner">user wins!!!</h1>
                        {% else %}
                            <h1 class="winner">match ties!!!</h1>
                        {% endif %}
                        <div class="scorecard">
                            <h2>Matchs: {{match_count}}</h2>
                            <h2>Player score: {{points_user}}</h2>
                            <h2>Computer score: {{points_ai}}</h2>
                        </div>
                </div>
                
                <a href="{% url 'opencv' %}"><button class="back-btn"><span class="span"><--</span>back</button>
                </a>
            {% endif %}
        </main> 
    </div>
    
</body>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PROJECT</title>
    <link rel="stylesheet" href="\static\styles\home.css?{% now 'U' %}">
</head>

<body>
    <img src="{% static 'data\pexels-martin-péchy-304664.jpg' %}" class="bg">
    <nav>
        <img src="{% static '\data\logo.png' %}" alt="logo" class="logo">
        <h1 class="title">project-dj</h1>
        
        <div class="searchbar">
            <img src="{% static 'data/search (1).png' %}" alt="">
            <input type="text" class="search" placeholder="search here...">
        </div> 
        {% if user.is_authenticated %}
            {% if user.profile_image != "" %}
                <div class="profile">
                    <a href="{% url 'profile' %}"><img src={{user.profile_image}} class="profile_img" width="60px"></a>
                    <h5>@{{user}}</h5> 
                </div> 
            {% else %}
                <div class="profile">
                    <a href="{% url 'profile' %}"><img src="{% static 'data/user.png' %}" class="profile_img" width="60px"></a>
                    <h5>@{{user}}</h5> 
                </div> 
            {% endif %}
        {% else %}
        <div class="get_into">   
            <a href="{% url 'login' %}" class="login">login</a>
            <a href="{% url 'register' %}" class="signup"><button>signup</button></a>
        </div>
        {% endif %}
    </nav>
    <main>
        <article>
            <div class="text">
                <h1>Python Django Image Processing</h1>
                <p>
                    "Our hackathon project website is entirely built upon Python Django and focuses on image processing using Python. We have implemented various features to enhance user experience and encourage engagement with our content. Explore our website to discover the possibilities of image processing using Python Django!"
                </p>
            </div>
        </article>
        <div class="prj1 ">
            <div class="project-sector">
                    <div class="project_space"></div>
                        <div class="hidder">
                            <span><h5>{{project1.title}}</h5></span> 
                            <a href="{% url 'opencv'  %}" class="play_game"><button>Play Game</button></a>
                        </div>
                        <img src={{project1.template}} class="project_template" width="300px">
                    </div>
            </div>
        </div>
        <img src="{% static 'assests/next.png' %}" class="next" width="50px">
        <img src="{% static 'assests/previous.png' %}" class="previous" width="50px">
        <div class="prj2">
            </article>
            <div class="project-sector">
                    <div class="project_space"></div>
                        <div class="hidder">
                            <span><h5>{{project2}}</h5></span> 
                            <a href="{% url 'object_detector' %}" class="play_game"><button>DECTECT</button></a>
                        </div>
                        <img src="{% static 'data/dector.gif' %}" class="project_template" width="300px">
                    </div>
            </div>
        </div>
    </main>
    <script src="{% static 'scripts/home.js' %} "></script>
</body>
</html>

templates/login_register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if mode == 'edit' %}
        <link rel="stylesheet" href="/static/styles/signup_edit.css? {% now 'U' %}" >
    {% else %}
        <link rel="stylesheet" href="/static/styles/login_registraion.css? {% now 'U' %}" >
    {% endif %}
    <title>
        {% if form_name == 'register' %}
             REGISTER
        {% else %}
            LOGIN
        {% endif %}

    </title>
</head>
<body> 
    <header>
        <a href="/" class="home"><button> Home </button></a>
        <h1>project-dj</h1>
        
    </header>

    <div class="content">
        <div class="headline">
            {% if form_name == 'register' %}
                <h1>Signup</h1>
            {% else %}
                <h1>Login</h1>
            {% endif %}
        </div>
        <div class="headline-image">
            {% if form_name == 'register' %}
                <img src="\static\assests\registraionimges.png" alt="" srcset="">
            {% else %}
                <img src="\static\assests\login.jpg" alt="" srcset="">
            {% endif %}
        </div>

    </div>
    <div class="container">

        {% if form_name == 'register' %}
        <form action="" method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="submit">SUBMIT</button>
            <div class="login_redirect">
                <p>Already has an account? <a href="{% url 'login' %}">Login</a> </p>
            </div>
            
        </form>
        {% else %}
        <form action="" method="post" enctype='multipart/form-data'>
            {% csrf_token %}
                <p>
                    <label for="">Email:</label>
                    <input type="email" name="email">
                </p>
                <p>
                    <label for="">Password: </label> 
                    <input type="password" name="password">
                </p>
                <button type="submit" class="submit">SUBMIT</button>  
                <div class="login_redirect">
                    <p>Doesn't have an account?<a href="{% url 'register' %}">Signup</a></p> 
                </div>
        </form>
        {% endif %} 

    </div>
    <script src="static/scripts/register.js"></script>
</body>
</html>

templates/object_detecter.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>object_detecter</title>
    <link rel="stylesheet" href="\static\styles\object_detector.css?{% now 'U' %}">
</head>
<body>
    <a href="/" class="home"><button> Home </button></a>
    <img src="{% static '\assests\wallpaper.jpg' %}">
    <main>
            <div class="compartment1">
                <h1>"Image Object Recognition: Instantly Identify Objects within Your Images"</h1>
                <p>
                    Your website page allows users to upload an image from their computer or device. Once the image is uploaded, the website utilizes a computer vision algorithm to identify the objects within the image. The identified objects are then displayed on the website page, along with their corresponding labels.
                    
                    In addition to displaying the identified objects, the website also provides users with the option to view the original image and the identified objects side by side. This could be done by displaying the original image and overlaying the identified objects with bounding boxes or highlighting them in some other way.
                    
                    Overall, your website page provides a convenient and user-friendly way for individuals to identify objects within their images, making it easier for them to understand and analyze the visual content they have.</p>
                <form action="" method="post" enctype='multipart/form-data'>
                    {% csrf_token %}
                    <input type="file" name="image" id="id_image">
                    <button type="submit"> Launch </button>
                </form>
            </div>
            <div class="compartment2">
                {% if mode != 'display' %}
                <h3>Detected objects</h3>
                {% else %}
                    <div class="h4">
                        <p>objects</p>
                        {% for label in label %}
                            <h4>{{label}}</h4>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

    </main>
</body>
</html>

templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PROFILE</title>
    <link rel="stylesheet" href="static/styles/profile.css? {% now 'U' %}">
</head>
<body>
    
    <img src="{% static 'data/bg2.jpg' %}" class="bg">
    <div class="container ">
        <a href="/" class="home"><button> Home </button></a>
        <div class="edit logout">
            <a href="{% url 'logout' %}"><button class="logout" >Logout</button></a>
        </div>
        <div class="edit">
            <a href="{% url 'signup_edit' %}"><button class="edit" >Edit</button></a>
        </div>
        <div class="camera">
        <img src="{% static  'data/camera.png'%}" alt="" srcset="" name="img" class="popup_initiliser ">
    </div>
        {% if user.profile_image == '' %}
            <img src="{% static 'data/user.png' %}" class="profile_image">
        {% else %}
            <img src={{user.profile_image}} class="profile_image">
        {% endif %}
        <div class="text_part">
            <h1 class="username">@{{user}}</h1>
            <h3 class="email">email: <span>{{user.email}}</span></h3>
            {% if user.firstname == none %}
                <h3 class="firstname">firstname: <span> --- </span></h3>
            {% else %}
                <h3 class="firstname">firstname: <span>{{user.firstname}}</span></h3>
            {% endif %}
            {% if user.lastname == none %}
                <h3 class="lastname">lastname:<span> --- </span></h3>
            {% else %}
                <h3 class="lastname">lastname: <span>{{user.lastname}}</span></h3>
            {% endif %}
        </div>
    </div>
    <div class="summa"></div>
    <div class="popup">
        <div class="dj">
            <div class="exit">
                <img src="{% static 'data/close.png' %}" alt="" srcset="" class="popup_exit">
            </div>
            <div class="h1">
            <h1>Project-dj</h1></div>
            <div class="h3">
            <h3>Profile Picture</h3></div>
            <div class="p"><p>A picture helps people recognize you and lets you know when you’re signed in to your account</p></div>
            {% if user.profile_image == '' %}
                <img src="{% static 'data/user.png' %}" class="edit_profile_image">
            {% else %}
                <img src={{user.profile_image}} class="edit_profile_image">
            {% endif %}
            <div class="end">
                    <button type="submit" class="change">Change</button>
                    <form action="" method="post">
                        {% csrf_token %}
                        <button type="submit" name="remove">remove</button>
                    </form>
            </div>
        </div>
    </div>
    <div class="get_image">
        <div class="get_image_exit">
            <img src="{% static 'data/close.png' %}" alt="" srcset="" class="image_getter_exit" >
        </div>
        <div class="h1">
            <h1>Project-dj</h1>
        </div>
        <div class="h3 h3_move">
            <h3>Change picture</h3>
        </div>
        <form method="post" enctype="multipart/form-data" >
            {% csrf_token %}
                <input type="file" name="image" class="chose_image" id="id_image">
                <button type="submit" class="submit-btn">submit</button>
        </form> 
    </div>
    <script src="{% static 'scripts/profile.js' %}"></script>
</html>

templates/project.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PROJECT</title>
</head>
<body>
    <img src="{% static template %}" alt="">
</body>
</html>

templates/signup_edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/styles/signup_edit.css? {% now 'U' %}" >
    <title>
        SIGNUP-EDIT
    </title>
</head>
<body> 
    <header>
        <a href="/" class="home"><button> Home </button></a>
        <a href="/"><h1>project-dj</h1></a>
    </header>

    <div class="content">
        <div class="headline">
            <h1>Edit-Profile</h1>
        </div>
        <div class="headline-image">
            <img src="\static\assests\registraionimges.png" alt="" srcset="">
        </div>

    </div>
    <div class="container">

        <form action="" method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            <p>
                <label for="id_email">Email:</label>
                <input type="email" name="email" value={{form.email}} maxlength="100" required="" id="id_email">
              </p>
              <p>
                <label for="id_username">Username:</label>
                <input type="text" name="username" value={{form.username}} maxlength="100" required="" id="id_username">
              </p>
              <p>
                <label for="id_firstname">Firstname:</label>
                <input type="text" name="firstname" value={{form.firstname}} maxlength="100" id="id_firstname">
              </p>
              <p>
                <label for="id_lastname">Lastname:</label>
                <input type="text" name="lastname" value={{form.lastname}} maxlength="100" id="id_lastname">
              </p>
            <button type="submit" class="submit">SUBMIT</button>
            <div class="login_redirect">
                <p>Already has an account? <a href="{% url 'login' %}">Login</a> </p>
            </div>
            
        </form>

    </div>
    <script src="static/scripts/register.js"></script>
</body>
</html>